#!/bin/bash

function header_install () {
    clear &&
    echo "                                                       /yy"
    echo "                                                      |__/"
    echo "  /yyyyyyy  /yyyyyy   /yyyyyy   /yyyyyy  /yyyyyy/yyyy  /yy"
    echo " /yy_____/ /yy__  yy /yy__  yy |____  yy| yy_  yy_  yy| yy"
    echo "| yy      | yy  \__/| yyyyyyyy  /yyyyyyy| yy \ yy \ yy| yy"
    echo "| yy      | yy      | yy_____/ /yy__  yy| yy | yy | yy| yy"
    echo "|  yyyyyyy| yy      |  yyyyyyy|  yyyyyyy| yy | yy | yy| yy"
    echo " \_______/|__/       \_______/ \_______/|__/ |__/ |__/|__/"
    echo ""
    echo "+------------+--------------------------------------------------+"
    echo "|                  LINUX EYERISE INSTALATION                    |"
    echo "+------------+--------------------------------------------------+"
    echo "| Author     |  Al Muhdil Karim                                 |"
    echo "| Mainteners |  Ibnu Dzaki                                      |"
    echo "| Version    |  v0.01                                           |"
    echo "| License    |  BSD 2-Clause Simplified License                 |"
    echo "+------------+--------------+-----------------------------------+"
}

